// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppUsageStats(arg1) {
  return window['go']['ipc']['AgentIPCBridge']['GetAppUsageStats'](arg1);
}

export function GetCurrentActiveApp() {
  return window['go']['ipc']['AgentIPCBridge']['GetCurrentActiveApp']();
}

export function GetCurrentActiveBrowser() {
  return window['go']['ipc']['AgentIPCBridge']['GetCurrentActiveBrowser']();
}

export function GetCurrentActiveFocus() {
  return window['go']['ipc']['AgentIPCBridge']['GetCurrentActiveFocus']();
}

export function GetDomainUsageStats(arg1) {
  return window['go']['ipc']['AgentIPCBridge']['GetDomainUsageStats'](arg1);
}

export function GetRecentAppActivities(arg1) {
  return window['go']['ipc']['AgentIPCBridge']['GetRecentAppActivities'](arg1);
}

export function GetRecentBrowserActivities(arg1) {
  return window['go']['ipc']['AgentIPCBridge']['GetRecentBrowserActivities'](arg1);
}

export function GetRecentScreenshots(arg1) {
  return window['go']['ipc']['AgentIPCBridge']['GetRecentScreenshots'](arg1);
}

export function GetScreenshotBase64(arg1) {
  return window['go']['ipc']['AgentIPCBridge']['GetScreenshotBase64'](arg1);
}

export function GetScreenshotInterval() {
  return window['go']['ipc']['AgentIPCBridge']['GetScreenshotInterval']();
}

export function GetServicesStatus() {
  return window['go']['ipc']['AgentIPCBridge']['GetServicesStatus']();
}

export function GetUnifiedActivities(arg1) {
  return window['go']['ipc']['AgentIPCBridge']['GetUnifiedActivities'](arg1);
}

export function RestartService(arg1) {
  return window['go']['ipc']['AgentIPCBridge']['RestartService'](arg1);
}

export function SetScreenshotInterval(arg1) {
  return window['go']['ipc']['AgentIPCBridge']['SetScreenshotInterval'](arg1);
}

export function StartService(arg1) {
  return window['go']['ipc']['AgentIPCBridge']['StartService'](arg1);
}

export function StopService(arg1) {
  return window['go']['ipc']['AgentIPCBridge']['StopService'](arg1);
}

export function TakeScreenshotNow() {
  return window['go']['ipc']['AgentIPCBridge']['TakeScreenshotNow']();
}
