// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetAppUsageStats(arg1:number):Promise<Array<models.AppUsageStat>>;

export function GetCurrentActiveApp():Promise<models.AppActivity>;

export function GetCurrentActiveBrowser():Promise<models.BrowserActivity>;

export function GetCurrentActiveFocus():Promise<models.UnifiedActivity>;

export function GetDomainUsageStats(arg1:number):Promise<Array<models.BrowserUsageStat>>;

export function GetRecentAppActivities(arg1:number):Promise<Array<models.AppActivity>>;

export function GetRecentBrowserActivities(arg1:number):Promise<Array<models.BrowserActivity>>;

export function GetRecentScreenshots(arg1:number):Promise<Array<models.ScreenshotRecord>>;

export function GetScreenshotBase64(arg1:string):Promise<string>;

export function GetScreenshotInterval():Promise<number>;

export function GetServicesStatus():Promise<Record<string, models.ServiceStatus>>;

export function GetUnifiedActivities(arg1:number):Promise<Array<models.UnifiedActivity>>;

export function RestartService(arg1:string):Promise<boolean|string>;

export function SetScreenshotInterval(arg1:number):Promise<string>;

export function StartService(arg1:string):Promise<boolean|string>;

export function StopService(arg1:string):Promise<boolean|string>;

export function TakeScreenshotNow():Promise<boolean|string>;
